---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: basic-springboot-app
  description: "team-a: basic-springboot-app"
  annotations:
    argocd/app-selector: "team-a-gitops=basic-springboot-app"
    argocd/app-namespace: team-a-gitops
    janus-idp.io/tekton: basic-springboot-app
    backstage.io/kubernetes-id: basic-springboot-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=basic-springboot-app'
    sonarqube.org/project-key: ci-pipeline-ref-basic-springboot-app
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
