---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: basic-springboot-app
  description: "team-a: basic-springboot-app"
  annotations:
    argocd/app-selector: "team-a-cicd=basic-springboot-app"
    argocd/app-namespace: team-a-cicd
    argocd/instance-name: team-a-cicd
    janus-idp.io/tekton: basic-springboot-app
    backstage.io/kubernetes-id: basic-springboot-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=basic-springboot-app'
    sonarqube.org/project-key: ci-pipeline-ref-basic-springboot-app
    github.com/project-slug: devhub-showcase/basic-springboot-app
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://devspaces.apps.dev-acm.v3socp.boo/#https://github.com/devhub-showcase/basic-springboot-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
