---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: batman
  description: "dc: batman"
  annotations:
    argocd/app-selector: "dc-gitops=batman"
    argocd/app-namespace: dc-gitops
    backstage.io/kubernetes-id: batman
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=batman'
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
