---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: basic-springboot-app
  description: "team-uno: basic-springboot-app"
  annotations:
    argocd/app-selector: "team-uno-cicd=basic-springboot-app"
    argocd/app-namespace: team-uno-cicd
    janus-idp.io/tekton: basic-springboot-app
    backstage.io/kubernetes-id: basic-springboot-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=basic-springboot-app'
    sonarqube.org/project-key: ci-pipeline-ref-basic-springboot-app
  links:
    - url: https://devspaces.apps.dev-acm.v3socp.boo/#https://github.com/devhub-showcase/basic-springboot-app?devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
spec:
  type: resources
  lifecycle: production
  owner: group:default/ops
